name: pushup_bro
description: Track your pushups with ease using the sensors in your AirPods!
publish_to: "none"

version: 2.0.0+4

environment:
  sdk: ">=3.3.3"

dependencies:
  animated_flip_counter: ^0.3.4
  audioplayers: ^6.0.0
  carbon_icons: ^0.0.1+2
  carousel_slider: ^4.2.1
  circular_clip_route: ^0.2.0+3
  # cloud_firestore: ^5.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  # firebase_app_check: ^0.3.0
  # firebase_auth: ^5.0.0
  # firebase_core: ^3.0.0
  # firebase_crashlytics: ^4.0.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_airpods: ^1.0.3
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: any
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  liquid_swipe: ^3.0.0
  modal_bottom_sheet: ^3.0.0-pre
  path_provider: ^2.1.3
  rive: ^0.13.5
  shared_preferences: ^2.0.17
  table_calendar: ^3.0.8
  url_launcher: ^6.1.9

dev_dependencies:
  build_runner: ^2.4.11
  dart_code_metrics: ^5.7.6
  flutter_gen_runner: ^5.1.0+1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  very_good_analysis: ^5.1.0

dependency_overrides:
  watcher: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/fonts/
    - assets/images/
    - assets/images/island/
    - assets/images/island/accessories/
    - assets/images/island/quests/
    - assets/images/island/quests/intro/
    - assets/images/island/quests/jungle/
    - assets/rive/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 700
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: assets/l10n
  ouput_dir: lib/generated

flutter_gen:
  output: lib/generated/
  line_length: 80

  integrations:
    rive: true
